#!/usr/bin/env node
// Release notes, carrying rf-harness's accuracy table (ticket W5-05
// criterion 3; docs/TESTING.md §5's note).
//
// The table is READ from docs/evidence/local-gate.json rather than
// recomputed here. That file is produced by rf-harness's own
// local-gate-evidence binary and is refused by validate-evidence unless
// it was generated from a clean tree — so the numbers in a release note
// are the numbers a real gate run produced, not a second implementation
// that could drift from it. One source of truth, and it is the one that
// already has a validator pointed at it.
//
// Usage: release-notes.mjs <version> <commit> <host> <priorFixtures>
//                          <drillStatus> <archivedCount>
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..");

const [version, commit, host, priorFixtures, drillStatus, archived] =
  process.argv.slice(2);

if (!version) {
  console.error("usage: release-notes.mjs <version> <commit> <host> ...");
  process.exit(2);
}

let evidence = null;
try {
  evidence = JSON.parse(
    readFileSync(join(repoRoot, "docs/evidence/local-gate.json"), "utf8"),
  );
} catch {
  console.error("release-notes: docs/evidence/local-gate.json missing or unreadable");
  console.error("  run scripts/local-gate.sh first — the accuracy table comes from it");
  process.exit(1);
}

const table = evidence.accuracy_table ?? { rows: [], raw: {}, effective: {} };
const rows = table.rows ?? [];

// Group by suite so the table reads as suites rather than as 31 loose
// rows; the per-ROM detail is what the evidence file is for.
const bySuite = new Map();
for (const r of rows) {
  const k = `${r.suite}|${r.console}|${r.fr}|${r.tier}`;
  const g = bySuite.get(k) ?? { ...r, n: 0, pass: 0 };
  g.n += 1;
  if (r.status === "pass") g.pass += 1;
  bySuite.set(k, g);
}

const lines = [];
lines.push(`# RetroForge ${version}`);
lines.push("");
lines.push(`Commit \`${commit}\``);
lines.push("");

lines.push("## Accuracy");
lines.push("");
lines.push(
  `Generated by rf-harness, read from \`docs/evidence/local-gate.json\` — ` +
    `the same file \`validate-evidence\` refuses unless it came from a clean tree.`,
);
lines.push("");
lines.push("| suite | console | requirement | tier | result |");
lines.push("|---|---|---|---|---|");
for (const g of [...bySuite.values()].sort((a, b) => a.suite.localeCompare(b.suite))) {
  const ok = g.pass === g.n;
  lines.push(
    `| ${g.suite} | ${g.console} | ${g.fr} | ${g.tier} | ${ok ? "pass" : "**FAIL**"} ${g.pass}/${g.n} |`,
  );
}
lines.push("");
const eff = table.effective ?? {};
lines.push(`**${eff.pass ?? 0} of ${eff.total ?? 0} ROMs/suites passing.**`);
lines.push("");
lines.push(
  `Vectors: nes6502 ${evidence.vectors?.total_pass ?? 0}/${
    (evidence.vectors?.total_pass ?? 0) + (evidence.vectors?.total_fail ?? 0)
  } cases · nestest ${evidence.nestest?.lines_matched ?? 0}/${
    evidence.nestest?.lines_compared ?? 0
  } lines.`,
);
lines.push("");

lines.push("## Save-state migration drill");
lines.push("");
if (Number(priorFixtures) === 0) {
  lines.push(
    `**${drillStatus}** — 0 previously archived fixtures. This release ` +
      `ESTABLISHES the baseline that the next one drills against. Recorded ` +
      `rather than skipped: a drill that quietly does nothing is how ` +
      `FR-STATE-005 becomes ceremonial, which is what R-F3 exists to prevent.`,
  );
} else {
  lines.push(
    `**${drillStatus}** — every one of ${priorFixtures} previously archived ` +
      `\`.rfstate\` fixtures still loads on this build (FR-STATE-005, R-F3).`,
  );
}
lines.push("");
lines.push(`${archived} fixture(s) archived into \`fixtures/releases/${version}/\`.`);
lines.push("");

lines.push("## Artifacts");
lines.push("");
lines.push(`Built and runnable here: \`${host}\`.`);
lines.push("");
lines.push(
  "**Not produced, and why.** The macOS/Windows/Linux matrix needs machines " +
    "this project does not have. GitHub Actions is out of budget permanently " +
    "(ruling 2026-08-22) and cross-building Windows and Linux from the darwin " +
    "dev machine is not a substitute: wgpu makes it awkward, and an artifact " +
    "nobody has RUN on the target OS is not evidence of a release. A " +
    "self-hosted runner or Gitea Actions would restore it; both are free and " +
    "neither is set up.",
);
lines.push("");

console.log(lines.join("\n"));
