//! Ticket W1-04b, acceptance criterion 2: "renders correct BG for a fixture
//! golden frame" — and, per the ticket brief, THE oracle W1-04a's own tests
//! never had: an independently-computed expected frame, compared against
//! what `rf_nes`'s real CPU+PPU+bus actually render from a synthetic NROM
//! image, byte for byte.
//!
//! ## Why this test lives in `rf-harness`, not `rf-nes`
//!
//! `crates/rf-nes/src/ppu/**` (this ticket's other write-scope root) has no
//! way to *run a ROM* — building a `NesBus`, powering on a real `Cpu`
//! against it, and hashing the drained frame needs `rf-harness`'s
//! `golden_frame` helpers (`hash_frame_palette_indices`), which is exactly
//! why the conductor's scope note widened this ticket to include
//! `crates/rf-harness/**`. `rf-harness` already depends on `rf-nes`
//! directly (`Cargo.toml`'s own comment, ticket W0-07's layer-rule
//! exemption for "the test harness").
//!
//! ## Why this fixture is trustworthy as an oracle
//!
//! The expected frame below is computed by a closed-form formula over
//! `(tile_row, tile_col)` alone — never by running this crate's own PPU and
//! recording whatever came out. That distinction matters: a golden
//! generated by "run it once, save the result" would silently canonize
//! whatever W1-04a's pipeline happens to produce, including a real bug (the
//! ticket's own warning: "if your golden frame comes out shifted... that is
//! a REAL BUG... not a golden you should regenerate to match"). Computing
//! the expected grid analytically, from the exact same nametable/attribute/
//! CHR bytes the fixture ROM's own program pokes into PPU memory, is what
//! makes a mismatch meaningful instead of circular.
//!
//! ## Fixture design: why a shift or scanline-boundary bug can't hide
//!
//! Every 8x8 background tile is a **solid fill** (uniform pattern bits
//! across all 8 rows/columns of the tile), so within one tile every pixel
//! must read the exact same palette value — any single wrong pixel is
//! therefore a real bug, not fine-X noise. The nametable tile index is
//! `tile_index(row, col) = row*37 + col*7 + 11 (mod 256)`; 37 and 7 are
//! both coprime with 256, so incrementing `col` by 1 always changes the
//! index by 7 (mod 256) and incrementing `row` by 1 always changes it by 37
//! (mod 256) — no two of this fixture's 30 rows or 32 columns ever produce
//! the same index by coincidence, so a whole-tile horizontal shift, a wrong
//! tile at a scanline-row boundary (dot 256's Y-increment / dot 257's
//! horizontal copy), or a wrong first tile of the frame (the pre-render
//! line's dots 321-336 prefetch — the exact thing W1-04a's own tests left
//! unproven) all change the rendered value at that position instead of
//! aliasing to another valid answer.
use rf_core_api::{CoreEvent, CoreSink, PixelLayer, PpuPixel};
use rf_harness::hash_frame_palette_indices;
use rf_nes::{Cpu, NesBus};

const SCREEN_WIDTH: u16 = 256;
const SCREEN_HEIGHT: u16 = 240;
const TILE_ROWS: u8 = 30; // 240 / 8
const TILE_COLS: u8 = 32; // 256 / 8

// ---------------------------------------------------------------------
// Oracle: the fixture's own geometry, computed independently of anything
// in `rf_nes::ppu` (a different crate — there is nothing to call into even
// if this test wanted to).
// ---------------------------------------------------------------------

/// The nametable byte this fixture writes at `(row, col)` (see this file's
/// module doc for why 37/7/11 were chosen).
fn tile_index(row: u8, col: u8) -> u8 {
    row.wrapping_mul(37)
        .wrapping_add(col.wrapping_mul(7))
        .wrapping_add(11)
}

/// The 2-bit pattern code this fixture's CHR data encodes for tile `t`,
/// always nonzero (1-3) so a background pixel is never accidentally forced
/// to the backdrop (nesdev.org/wiki/PPU_rendering's "Priority multiplexer":
/// pattern bits `00` always mean transparent, regardless of attribute).
fn pattern_code(t: u8) -> u8 {
    1 + (t % 3)
}

/// The 2-bit attribute value this fixture's single constant attribute byte
/// (`0xE4 = 0b11_10_01_00`) yields for tile `(row, col)`, derived directly
/// from nesdev.org/wiki/PPU_scrolling's quadrant selection (2x2-tile
/// quadrants of a 4x4-tile attribute block, selected by bit 1 of coarse X
/// and bit 1 of coarse Y): quadrant bits `0b00`(TL)=0, `0b01`(TR)=1,
/// `0b10`(BL)=2, `0b11`(BR)=3 — exactly `0xE4`'s four 2-bit fields in
/// order.
fn attr_value(row: u8, col: u8) -> u8 {
    let col_quadrant = (col >> 1) & 1;
    let row_quadrant = (row >> 1) & 1;
    (row_quadrant << 1) | col_quadrant
}

/// Expected `palette_index` at screen pixel `(x, y)`: since this fixture's
/// palette RAM is seeded with `palette[i] = i` for `i in 0..16` (see
/// `write_palette_setup`), the emitted pixel value *is* the palette
/// address, `(attr << 2) | pattern`.
fn expected_pixel(x: u16, y: u16) -> u8 {
    let row = (y / 8) as u8;
    let col = (x / 8) as u8;
    (attr_value(row, col) << 2) | pattern_code(tile_index(row, col))
}

fn expected_frame() -> Vec<Vec<u8>> {
    (0..SCREEN_HEIGHT)
        .map(|y| (0..SCREEN_WIDTH).map(|x| expected_pixel(x, y)).collect())
        .collect()
}

// ---------------------------------------------------------------------
// CHR (pattern table) data: one solid-fill 8x8 tile per tile index 0-255,
// encoding `pattern_code(t)` uniformly across every row and column.
// ---------------------------------------------------------------------

fn build_chr() -> Vec<u8> {
    const CHR_BANK_SIZE: usize = 8 * 1024;
    let mut chr = vec![0u8; CHR_BANK_SIZE]; // 1 CHR bank; only the first 4 KiB (256 tiles) is used
    for t in 0..=255u8 {
        let code = pattern_code(t);
        let lo_fill = if code & 1 != 0 { 0xFFu8 } else { 0x00u8 };
        let hi_fill = if (code >> 1) & 1 != 0 { 0xFFu8 } else { 0x00u8 };
        let base = t as usize * 16;
        for row in 0..8 {
            chr[base + row] = lo_fill;
            chr[base + 8 + row] = hi_fill;
        }
    }
    chr
}

// ---------------------------------------------------------------------
// A minimal hand-assembled 6502 program (LDA #imm / STA $abs / JMP $abs
// only — no branches, so no relative-offset arithmetic to get wrong) that
// pokes the nametable, attribute table, and palette RAM through the real
// $2006/$2007 register protocol, then spins in an infinite self-jump loop
// with background rendering enabled.
// ---------------------------------------------------------------------

fn lda_imm(prg: &mut Vec<u8>, v: u8) {
    prg.push(0xA9);
    prg.push(v);
}

fn sta_abs(prg: &mut Vec<u8>, addr: u16) {
    prg.push(0x8D);
    prg.push((addr & 0xFF) as u8);
    prg.push((addr >> 8) as u8);
}

fn jmp_abs(prg: &mut Vec<u8>, addr: u16) {
    prg.push(0x4C);
    prg.push((addr & 0xFF) as u8);
    prg.push((addr >> 8) as u8);
}

/// Build the 16 KiB PRG bank (mapped at `$8000`, mirrored to `$C000`) and
/// return `(prg_bytes, idle_loop_addr)` — the address of the trailing
/// `JMP` instruction, which the test drives `Cpu::step` until `cpu.pc`
/// reaches, as the signal that setup has finished.
fn build_prg() -> (Vec<u8>, u16) {
    const PRG_BASE: u16 = 0x8000;
    let mut prg = Vec::new();

    // --- nametable: $2006 -> $2000, then 960 bytes (32 cols x 30 rows) ---
    lda_imm(&mut prg, 0x20);
    sta_abs(&mut prg, 0x2006);
    lda_imm(&mut prg, 0x00);
    sta_abs(&mut prg, 0x2006);
    for row in 0..TILE_ROWS {
        for col in 0..TILE_COLS {
            lda_imm(&mut prg, tile_index(row, col));
            sta_abs(&mut prg, 0x2007);
        }
    }
    // Auto-increment (+1, PPUCTRL bit 2 clear) has now walked the PPU
    // address from $2000 to exactly $23C0 (2000 + 30*32 = 23C0) -- the
    // attribute table's own start, so no extra $2006 write is needed.

    // --- attribute table: 64 bytes, one constant value (see attr_value's doc) ---
    lda_imm(&mut prg, 0xE4);
    for _ in 0..64 {
        sta_abs(&mut prg, 0x2007);
    }

    // --- palette: $2006 -> $3F00, then 16 bytes, palette[i] = i ---
    lda_imm(&mut prg, 0x3F);
    sta_abs(&mut prg, 0x2006);
    lda_imm(&mut prg, 0x00);
    sta_abs(&mut prg, 0x2006);
    for i in 0..16u8 {
        lda_imm(&mut prg, i);
        sta_abs(&mut prg, 0x2007);
    }

    // --- scroll reset: $2000 = 0 (clears t's nametable-select bits, which
    // the palette $2006 write above left at 3 -- ticket W1-04b pre-flight
    // finding), then $2005 x2 = 0,0 (t <- 0 entirely: coarse X/Y, fine
    // X/Y all zero) ---
    lda_imm(&mut prg, 0x00);
    sta_abs(&mut prg, 0x2000);
    sta_abs(&mut prg, 0x2005); // A still 0
    sta_abs(&mut prg, 0x2005);

    // --- enable background rendering (show bg + show bg in leftmost 8px) ---
    lda_imm(&mut prg, 0x0A);
    sta_abs(&mut prg, 0x2001);

    // --- idle loop: JMP to self ---
    let idle_addr = PRG_BASE + prg.len() as u16;
    jmp_abs(&mut prg, idle_addr);

    (prg, idle_addr)
}

fn build_rom() -> (Vec<u8>, u16) {
    let (mut prg, idle_addr) = build_prg();
    const PRG_BANK_SIZE: usize = 16 * 1024;
    assert!(
        prg.len() + 4 <= PRG_BANK_SIZE,
        "fixture program ({} bytes) must fit in one 16 KiB PRG bank, with room for the reset vector",
        prg.len()
    );
    prg.resize(PRG_BANK_SIZE, 0xEA); // NOP-pad (never reached: the idle loop traps first)
    prg[PRG_BANK_SIZE - 4] = 0x00; // reset vector low -> $8000
    prg[PRG_BANK_SIZE - 3] = 0x80; // reset vector high

    let mut rom = Vec::new();
    rom.extend_from_slice(&rf_cart::nes::INES_MAGIC);
    rom.push(1); // 1 PRG bank (16 KiB)
    rom.push(1); // 1 CHR bank (8 KiB)
    rom.extend_from_slice(&[0u8; 10]); // flags6/7 + 8 reserved: mapper 0, horizontal mirroring
    rom.extend_from_slice(&prg);
    rom.extend_from_slice(&build_chr());
    (rom, idle_addr)
}

// ---------------------------------------------------------------------
// Capture: a permissive recorder (unlike `rf_harness::FrameCapture`, which
// panics on the scanline-0 wraparound between frames -- exactly what
// running many frames past the fixture's setup produces) plus a
// full-frame finder that locates the first complete, contiguous 0..239 run.
// ---------------------------------------------------------------------

#[derive(Default)]
struct PermissiveSink {
    rows: Vec<(u16, Vec<PpuPixel>)>,
}

impl CoreSink for PermissiveSink {
    fn video_scanline(&mut self, y: u16, pixels: &[PpuPixel]) {
        self.rows.push((y, pixels.to_vec()));
    }
    fn audio(&mut self, _samples: &[i16]) {}
    fn event(&mut self, _ev: CoreEvent) {}
}

/// Find the start index of the first run of `rows` whose `y` values are
/// exactly `0, 1, ..., height-1` in order.
fn find_full_frame(rows: &[(u16, Vec<PpuPixel>)], height: usize) -> Option<usize> {
    for start in 0..rows.len() {
        if rows[start].0 != 0 {
            continue;
        }
        if start + height > rows.len() {
            return None;
        }
        let is_full_run = rows[start..start + height]
            .iter()
            .enumerate()
            .all(|(i, (y, _))| *y == i as u16);
        if is_full_run {
            return Some(start);
        }
    }
    None
}

#[test]
fn synthetic_nrom_background_matches_the_analytically_computed_golden_frame() {
    let (rom_bytes, idle_addr) = build_rom();
    let mut bus = NesBus::from_ines_bytes(&rom_bytes).expect("valid synthetic NROM image");
    let mut cpu = Cpu::power_on(&mut bus);

    // Run setup (the fixture's own PRG code) until it reaches its trailing
    // self-jump loop.
    const SETUP_SAFETY_CAP: u32 = 200_000;
    let mut setup_steps = 0u32;
    while cpu.pc != idle_addr {
        cpu.step(&mut bus);
        setup_steps += 1;
        assert!(
            setup_steps < SETUP_SAFETY_CAP,
            "fixture setup never reached its idle loop (pc={:#06x}, expected {:#06x})",
            cpu.pc,
            idle_addr
        );
    }

    // Discard everything the PPU queued *during* setup (rendering was
    // disabled for almost all of it, and even the tail end is not
    // guaranteed to align to a scanline boundary) -- keeps the recorder
    // that follows unambiguous.
    let mut discard = PermissiveSink::default();
    bus.drain_video(&mut discard);

    // Now just spin in the idle loop for several frames' worth of dots.
    // JMP $abs is 3 CPU cycles/iteration; one frame is at most 262*341=
    // 89342 dots (~29781 CPU cycles); 60,000 iterations is >6 frames.
    for _ in 0..60_000 {
        cpu.step(&mut bus);
    }

    let mut capture = PermissiveSink::default();
    bus.drain_video(&mut capture);

    let start = find_full_frame(&capture.rows, SCREEN_HEIGHT as usize)
        .expect("at least one complete 240-scanline frame after the idle loop was reached");
    let frame_a = &capture.rows[start..start + SCREEN_HEIGHT as usize];

    let mut actual: Vec<Vec<u8>> = Vec::with_capacity(SCREEN_HEIGHT as usize);
    for (y, pixels) in frame_a {
        assert_eq!(
            pixels.len(),
            SCREEN_WIDTH as usize,
            "scanline {y} pixel count"
        );
        for (x, p) in pixels.iter().enumerate() {
            assert_eq!(
                p.layer,
                PixelLayer::Background(0),
                "scanline {y} pixel {x}: pattern is never 0 in this fixture, so it must never read as backdrop"
            );
        }
        actual.push(pixels.iter().map(|p| p.palette_index).collect());
    }

    let expected = expected_frame();

    // Pixel-level diagnostics first (a hash mismatch alone says nothing
    // about *where* the pipeline went wrong).
    for y in 0..SCREEN_HEIGHT as usize {
        for x in 0..SCREEN_WIDTH as usize {
            assert_eq!(
                actual[y][x],
                expected[y][x],
                "pixel ({x}, {y}): expected tile (row {}, col {})'s value, got a different one \
                 -- see this file's module doc for what a mismatch here means",
                y / 8,
                x / 8
            );
        }
    }

    // And the golden-frame hash compare this ticket's acceptance criterion
    // actually asks for, reusing `rf_harness::hash_frame_palette_indices`
    // rather than a second hashing implementation.
    let expected_hash = hash_frame_palette_indices(&expected, SCREEN_HEIGHT as usize);
    let actual_hash = hash_frame_palette_indices(&actual, SCREEN_HEIGHT as usize);
    assert_eq!(expected_hash, actual_hash);

    // Steady-state check: a static scene renders identically regardless of
    // odd/even frame parity (the skip changes total dot count, never pixel
    // content) -- confirm the NEXT complete frame hashes identically too.
    if start + 2 * SCREEN_HEIGHT as usize <= capture.rows.len() {
        let frame_b =
            &capture.rows[start + SCREEN_HEIGHT as usize..start + 2 * SCREEN_HEIGHT as usize];
        let is_contiguous = frame_b.iter().enumerate().all(|(i, (y, _))| *y == i as u16);
        assert!(is_contiguous, "frame B must also be a clean 0..239 run");
        let frame_b_indices: Vec<Vec<u8>> = frame_b
            .iter()
            .map(|(_, pixels)| pixels.iter().map(|p| p.palette_index).collect())
            .collect();
        let frame_b_hash = hash_frame_palette_indices(&frame_b_indices, SCREEN_HEIGHT as usize);
        assert_eq!(
            actual_hash, frame_b_hash,
            "a static scene must render identically on the next frame, odd or even"
        );
    }
}
